### ISSUE TITLE
Issue Ticket Process

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#51]
We should have clear and documented analysis, code, config and test. 
Tickets should be reviewed before closing them?

Since much of this work invovles configuration and load, my preference would be some short and simple shell scripts that could be used to automate the configuration. If someone had a VM or a laptop they want this stuff to run on, provided it is either Linux or Mac-os, or even a linux-subsystem in Windows, they pull a repo and run a script.

What do you think @joeflack4  @ShahimEssaid

**Comment by joeflack4** [comment]
Good idea creating an issue for this. It's administrative, but does need a decision.

I would say this is 2 different main themes / separate issues here: (i) review of code/tasks, (ii) QA / continuous integration.

For (i), I suggest a 4th, "Review" column for our kanban board(s). There is some project automation in GitHub that you can be pretty painlessly configured that can at least automatically put new pull requests in that column. We haven't got much code that we're actually writing, though, so won't be a lot of PRs. But we can manually add cards for things to review from "progress / sprint" to "review" (such as making sure that content uploaded is correct).

For (ii), I like GitHub actions as a solution for this. For the near-term scope of this QA automation, I think that would probably be better to just run unit tests on our production server rather than spin up a new one within the container that runs the GH action. This is because the setup / architecture is non-trivial and there are probably memory limitations on the GH action container.

**Comment by chrisroederucdenver** [comment]
4th column is a good idea. No pull request seems obvious, but even trivial ops, will be a commit. For example, consider searching for a term by either it's vocabulary's id or it's native FHIR id. It's done in Hapi, but we want to record that we know and have seen it work. Futhermore, we want a little demo line in the Jupyter notebook.

I was going to compare it to a less trivial implemenation like text search, which I think needs some conig. Obviously there's a commit to capture that. A test row in then notebook too.

**Comment by chrisroederucdenver** [comment]
Closing as too meta. This won't directly produce a positive (or negative) test case. moving to the TODO page.
