### ISSUE TITLE
Jan Connectathon: Server should be part of (yet undefined) playground

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#53]
## Overview
Mentioned in strategic plan for HL7. Playground also called "HL7 Foundry". It's a long-term effort, but also something is planned for it for the January Connectathon.

Implementation division has just started up, and is beginning to look at the playground.

**Comment by chrisroederucdenver** [comment]
We open tickets in an incomplete state and discuss them here to refine them. The closer to actionable a ticket can be, the better.  I'm closing this one because it is a little too far out in left field. 
I'm setting up some google docs for the project and this issue calls for a TODO list of issues that aren't quite ready for an issue ticket.
