### ISSUE TITLE
Synonyms

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#64]
In UMLS a CUI can have multiple AUIs, multiple strings, or synonyms as part of the same concept definition.
Can FHIR represent that? The issue then is, when doing text search, does the search go over each of the AUIs?

Which of our vocabularies and ontologies would have data like that?

IT SHOULD. It needs to.

(edit) [Detail evolving here ](https://docs.google.com/document/d/1u2Am0YC79yeouWf7l9s1ZyO821flTJxMT2ax4zpxRyU/edit#heading=h.2mvbivdnex4u)
(old link) [Detail evolving here ](https://docs.google.com/document/d/1slA9IMlFvtGyjr55sNzdn8qsKe7ch1Hz-vdazkFa8Fo/edit#
) where I so far have looked at the LOINC csv file and found less than what you get from the website.

**Comment by joeflack4** [comment]
I wonder if it is possible to do text search on synonyms.

**Comment by chrisroederucdenver** [comment]
😊 That’s where this all started!

From: Joe Flack ***@***.***>
Date: Monday, October 10, 2022 at 1:23 PM
To: HOT-Ecosystem/hapi-fhir-jpaserver-starter ***@***.***>
Cc: Roeder, Chris3 ***@***.***>, Author ***@***.***>
Subject: Re: [HOT-Ecosystem/hapi-fhir-jpaserver-starter] Synonyms (Issue #64)
[External Email - Use Caution]

I wonder if it is possible to do text search on synonyms.

**Comment by chrisroederucdenver** [comment]
- CodeSystem
  - Identifier: SNOMED
  - Property
    - Uri: [http://croeder.com/i_mean_what_is_say/alternate_text_representation](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fcroeder.com%2Fi_mean_what_is_say%2Falternate_text_representation&data=05%7C01%7CCHRIS.ROEDER%40cuanschutz.edu%7Cff7e2aa698bd421e429808daab01099b%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638010318199923354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FvXssLpwrQjc4%2Bpmr6Cxg5U23L9epgHCLHK87zc%2Fl0Y%3D&reserved=0)/1
    - Code: 1
    - (no system?)
    - Type: code
    - Description: short name
  - Property
    -Uri: [http://croeder.com/i_mean_what_is_say/alternate_text_representation](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fcroeder.com%2Fi_mean_what_is_say%2Falternate_text_representation&data=05%7C01%7CCHRIS.ROEDER%40cuanschutz.edu%7Cff7e2aa698bd421e429808daab01099b%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638010318199923354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FvXssLpwrQjc4%2Bpmr6Cxg5U23L9epgHCLHK87zc%2Fl0Y%3D&reserved=0)/2
    - Code: 2
    - (no system?)
    - Type: code
    - Description: consumer name
  - Property
    - Uri: [http://croeder.com/i_mean_what_is_say/alternate_text_representation](https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fcroeder.com%2Fi_mean_what_is_say%2Falternate_text_representation&data=05%7C01%7CCHRIS.ROEDER%40cuanschutz.edu%7Cff7e2aa698bd421e429808daab01099b%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638010318199923354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FvXssLpwrQjc4%2Bpmr6Cxg5U23L9epgHCLHK87zc%2Fl0Y%3D&reserved=0)/3
    - Code: 3
    - (no system?)
    - Type: code
    - Description: long common name
  - Concept
    - Code: 41657-
      - Display: Sodium(BldMV)[Moles/Vol]
      - Property
        - Code: 1,
        - Value: Sodium BldMV-SCnc
      - Property
        - Code: 2
        - Value: Sodium, Blood
      - Property
        - Code: 3
        - Value: Sodium [Mass/mass]

**Comment by joeflack4** [comment]
Just an update. I tried to configure [`aehrc/fhir-owl`](https://github.com/aehrc/fhir-owl) to include synonyms, but it did not work. I opened a [detailed issue](https://github.com/aehrc/fhir-owl/issues/10) about it.

Next steps: I thought about (a) writing a wrapper library around `aehrc/fhir-owl` to "simply" add in things that it is not including. However, parsing OWL could be a bit hairy. Option (b) is indeed writing a new `fhir-owl` library. I'm heavily leaning towards this for the reason that, in order to parse OWL for option _a_, I would convert to JSON (obographs format). But in doing so, from this step it would honestly be easier to straight up convert from that format to FHIR.

**Comment by chrisroederucdenver** [comment]
Why not fix fhir-owl?

**Comment by joeflack4** [comment]
That was my initial thought. There are some minor reasons why I'm against that, but the major reasons are:
1. I would probably change things in a way the author would not agree with.
  i.  It leaves a lot out: My default would be to include as much as possible from the source OWL, and leave things out that the user doesn't want. They are taking the opposite approach. Leaving most things out, and opting for the user to specify addition things to add. For example, I have to tell it to specifically add synonyms. OWL supports lots of other properties and relationships; not just synonyms. If I wanted to continue with their approach, I would be adding quite a lot to it and it would be quite time consuming as well.
  ii. It includes output I think should be left out: For example, every single class/node in the output includes these properties: `{"code": "root", "valueBoolean": false}, {"code": "deprecated", "valueBoolean": false}`. This isn't useless information, but it is very verbose. My preference would be to leave this type these kinds of `false` cases out and have them be implicit, and to have a CLI flag to include them only if I ask. That doesn't seem possible at the moment.

On the flip side, it looks a lot easier to roll my own `fhir-owl` than I'd first realized. This is because [`robot`](http://robot.obolibrary.org/convert) does most of the heavy lifting. It has an option to [convert](http://robot.obolibrary.org/convert) to [obographs JSON](https://github.com/geneontology/obographs/). I checked this out and it worked quite nicely. I haven't done an evaluation to see what properties/relationships (if any) that it leaves out. But the content retained in the JSON seems a lot richer than `fhir-owl` already. You can check out [mondo.obograph.json.zip](https://github.com/HOT-Ecosystem/hapi-fhir-jpaserver-starter/files/9793124/mondo.obograph.json.zip). It has the synonyms and more.

**Comment by chrisroederucdenver** [comment]
Wow. yeah, I didn't mean to insist on fhir-owl by my comments above. I just wanted a more clear presentation of the reasoning. In general principles. deciding to throw out code isn't one to make lightly. It's somewhat different here because Chris Mungall **_probably_** has an opinion worth listening to. 

In fact, I heard Chris Mungall's concerns about fhir-owl month's ago. That's why I kept mentioning pyrophen, but it doesn't do much and doesn't do synonyms. No surprise you're recommending Mungall's robot library. It's got to be much better.

**Comment by cmungall** [comment]
Here is the strategy in OAK, HTH:

OAK is generally data model neutral, but there are interfaces that assume a certain data model. E.g. the [OboGraph interface](https://incatools.github.io/ontology-access-kit/interfaces/obograph.html) assumes the obograph data model, including for synonyms.

Until recently this meant that you needed to conform to the OBO synonym model (OMO) for things like search by synonym to give complete results.

Recently there was a PR
https://github.com/INCATools/ontology-access-kit/pull/315

That allows you to pass a SSSOM that maps OMO predicates (including rdfs:label - anything OMO considers the standard) to your own custom predicates. Currently there are preconfigured mappings for SKOS. This adds a certain amount of complexity, but there is a necessarily complex situation here with a wild west of annotation properties.

Another possibility is that HOT adopts OMO, or HOT adopts some kind of OMO like standard data model for elements like synonyms, with standard annotation properties. Of course, not everyone will conform, but you can have a pre-processing step prior to loading, e.g. SPARQL CONSTRUCT. This keeps the API code simpler as it assumes uniform APs. Of course you are just pushing complexity upstream, so YMMV.

**Comment by joeflack4** [comment]
This is great news! I will evaluate OAK and [bioontologies](https://github.com/biopragmatics/bioontologies) for the `fhir-owl` bit that involves Obographs.

I'm mostly unfamiliar with OMO and YMMV, and so I'm not entirely following what you are saying here, but my initial plan is to support whatever structure that the source `.owl` comes in using [FHIR extensions](https://hl7.org/fhir/extensibility.html) wherever needed.

**Comment by chrisroederucdenver** [comment]
YMMV https://dictionary.cambridge.org/us/dictionary/english/ymmv

**Comment by chrisroederucdenver** [comment]
OMO, Obo Metadata Ontology, https://bioportal.bioontology.org/ontologies/OMO

**Comment by chrisroederucdenver** [comment]
@ShahimEssaid has a much better handle on this, but basically the synonyms end up in "label" designations  like those below. As I understand, searching for "use"s that have the synonym code, so you can fetch that value, need additional configuration. There's a resource, SearchParameterDefiniton, that lists these things that needs added to. I think it already has ways of searching for values from different languages.  
```    "designation": [ {
      "use": {
        "system": "http://snomed.info/sct",
        "code": "900000000000013009",
        "display": "Synonym (core metadata concept)"
      },
      "value": "CMV colitis"
    } ],

**Comment by joeflack4** [comment]
Good that you added this. I remember seeing this [`concept.designation.use`](https://build.fhir.org/codesystem-definitions.html#CodeSystem.concept.designation.use); can't remember if Shahim was the one that brought this up or if I saw it skimming through [CodeSystem](https://build.fhir.org/codesystem.html). Either way, pretty sure that (a) `designation` is how we are going to do it, as opposed to (b) the [custom property edges](https://github.com/HOT-Ecosystem/hapi-fhir-jpaserver-starter/issues/64#issuecomment-1276812743) way that I was thinking of doing it.

Although, hmm... It may be the case that the optimal thing to do is both (a) _and_ (b). Basically, I'm thinking that we want to capture the specific synonym type `e.g. oboInOwl:hasExactSynonym`, so (b) would be the way to do that. Although there is also another option (c), where we could use `designation.use` and add an `extension` element for the synonym type.

**Comment by chrisroederucdenver** [comment]
Hold on. These *are* exact synonyms because they are just alternate labels, so no predicate necessary. Furthermore,  the query you can or would write to do text search over the synonyms would dictate the representation. We want the one that *works* and is more simple.  We'll have to look at property and predicate searches for other things, so we'll have something to compare to, and evaluate the simplicity. And surely not both. We want to maintain a single source of truth when practical. 

Think about this: flexibility is good, but so is making a decision. Having two ways that mean the same thing is sort of ambiguous. Much like being Pythonic, right?

**Comment by joeflack4** [comment]
I don't disagree with that. I think the operative word in what I was trying to say was "e.g.". I was just using `oboInOwl:hasExactSynonym` because I can't remember offhand the other (common) synonym types. I think there are other ones, at least o.o. If not, then I agree we would only ever need to do this one way.

**Comment by chrisroederucdenver** [comment]
Basically a duplicate of Task 5 on issue #41
