### ISSUE TITLE
Focussed Easy OWL conversion: underscores or colons

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#69]
Restricting our focus to concepts, there are inconsistent ways of creating the codes for MONDO and HPO, likely from a difference between pyrophen and fhir-owl, or the way they are run. We should at least be consistent, but an educated choice would be good. 
I recently got (still need to read) a proposal by Jim Balhoff and Gaurav about this: Adding IRI Stems to the HL7 Terminology Website to Support Concept IRIs.

``` 
client.lookup_code(system='http://purl.obolibrary.org/obo/mondo.owl', code='MONDO_0008510')
client.lookup_code(system='http://purl.obolibrary.org/obo/hp.fhir', code='HP:0004409')

**Comment by joeflack4** [comment]
I feel like there are situations where the `_` vs `:` may come up (i.e. perhaps the CodeSystem being referenced hasn't been uploaded yet), but I believe the solution is to not use either, and simply use the the code (e.g. `0008510` in `MONDO_0008510`), along with its code system for a valid reference. If we really want to store the `curie_map` (set of prefixes / URI-stems (e.g. `MONDO -> http://purl.obolibrary.org/obo/mondo/`)), there is some standard in FHIR-RDF for where to put that, but I haven't taken a look yet.

@chrisroederucdenver Closing this for now because I believe the answer is to use the code as I described. If we do want an issue for figuring out where to put the `curie_map`, we can do that. If I'm wrong and this issue should remain open, @chrisroederucdenver feel free to do so.

**Comment by chrisroederucdenver** [comment]
https://bit.ly/fhir-rdf-concept-iris-july-2022

**Comment by joeflack4** [comment]
@chrisroederucdenver That document has helpful context and information. It title / main purpose appears to be "Adding IRI Stems to the HL7 Terminology Website", but I don't see anything about where this comes into play in the context of (i) the FHIR standard, (ii) alternative standards like representing RDF in FHIR, (iii) the role of such on a FHIR server. If we can find any of that information, I think it will be useful for determining what to do for this issue. But otherwise, I currently don't know what is actionable for us in this issue.
